# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
#image: docker:stable

pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        services:
          - docker
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - docker run -v $(pwd)/deploy:/deploy -w /deploy snezhig/deployer dep deploy
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
options:
  docker: true

definitions:
  services:
    docker:
      memory: 3072
