# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:8.0-fpm
pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Test'
        script:
          - apt-get update && apt-get install -qy git curl libzip-dev libpq-dev zip
          - docker-php-ext-install zip pdo pdo_mysql pdo_pgsql sockets
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate --no-interaction --force
          - ./vendor/bin/phpunit
        services:
          - postgres

  branches:
    production:
      - step:
          image: snezhig/deployer
          name: 'Deployment to Staging'
          deployment: staging
          script:
            - cd deploy
            - dep deploy -n

definitions:
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_PASSWORD: 'pipeline_password'
        POSTGRES_USER: 'pipeline_user'
        POSTGRES_DB: 'pipeline'
