# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: snezhig/deployer
pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Test'
        script:
          - cp .env.template .env
          - docker-compose build db php
          - docker-compose exec -u 1000 php php atrisan key:generate
        services:
          - docker
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - cd deploy
          - dep deploy -n
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
options:
  docker: true
