# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: snezhig/deployer
pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Test'
        script:
          - apt-get update && apt-get install -qy git curl libzip-dev zip autoconf
          - yes | pecl install redis
          - docker-php-ext-install pdo pdo_pgsql sockets zip
          - docker-php-ext-enable redis
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - ln -f -s .env.pipelines .env
          - php artisan migrate
          - ./vendor/bin/phpunit
        services:
          - postgres
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - cd deploy
          - dep deploy -n
    - step:
        name: 'Deployment to Production'
        deployment: production
        trigger: 'manual'
        script:
          - echo "Your deployment to production script goes here..."
definitions:
  services:
    postgres:
      image: mysql
      environment:
        MYSQL_DATABASE: 'pipeline_password'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_PASSWORD: 'pipeline_user'
        MYSQL_USER: 'pipeline'
