version: '3.7'

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build: ./.docker/images/php
    volumes:
      - ./:/var/www
      - ./.docker/images/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - socket:/sock
    working_dir: /var/www
    networks:
      - app-network
    links:
      - db
      - rabbit
      - mailhog
    environment:
      XDEBUG_CONFIG: client_host=${XDEBUG_CLIENT_HOST} client_port=${XDEBUG_CLIENT_PORT} remote_enable=1

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - "${INTERFACE:-127.0.0.1}:80:80"
    links:
      - php
    volumes:
      - ./:/var/www
      - ./.docker/images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/images/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/images/nginx/sites:/etc/nginx/sites-available
      - socket:/sock
    working_dir: /var/www
    networks:
      - app-network
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres
    command: [
        "postgres",
        "-c", "random_page_cost=1.1",
        "-c", "default_statistics_target=100",
        "-c", "effective_io_concurrency=200",
        "-c", "shared_buffers=500MB",
        "-c", "work_mem=32MB",
        "-c", "maintenance_work_mem=1GB",
        "-c", "effective_cache_size=11GB",
        "-c", "max_worker_processes=14",
        "-c", "max_parallel_workers_per_gather=4",
        "-c", "max_parallel_workers=14",
        "-c", "max_parallel_maintenance_workers=4",
    ]
    networks:
      - app-network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./.data/.db/postgres:/var/lib/postgresql/data
    ports:
      - "${INTERFACE:-127.0.0.1}:${DB_DOCKER_PORT}:${DB_PORT}"

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    image: mailhog/mailhog
    ports:
      - "${INTERFACE:-127.0.0.1}:3025:1025" # smtp server
      - "${INTERFACE:-127.0.0.1}:8025:8025" # web ui
    networks:
      - app-network

  rabbit:
    container_name: ${COMPOSE_PROJECT_NAME}_rabbitmq
    image: rabbitmq:3-management
    networks:
      - app-network
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_MQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_MQ_PASSWORD}
    ports:
      - "${RABBIT_MQ_PORT_EXTERNAL}:${RABBIT_MQ_PORT}"
      - "${RABBIT_UI_PORT_EXTERNAL}:${RABBIT_UI_PORT}"
volumes:
  socket:
    driver: local

networks:
  app-network:
    driver: bridge


